# Form implementation generated from reading ui file 'InterfazDefault3.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import BackgroundSesion2

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(544, 406)
        Dialog.setStyleSheet("background-image: url(:/images/fondo.jpg);\n"
"")
        self.frame1 = QtWidgets.QFrame(Dialog)
        self.frame1.setGeometry(QtCore.QRect(140, 20, 291, 371))
        self.frame1.setStyleSheet("#frame1{\n"
"background:rgba(0,0,0,0.8);\n"
"border-radius:15px;\n"
"border: 1px solid #990099;\n"
"}\n"
"\n"
"QLabel\n"
"{\n"
"color:white;\n"
"background:transparent;\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 0px 10px 14px -7px #e184f3;\n"
"    background:linear-gradient(to bottom, #c123de 5%, #a20dbd 100%);\n"
"    background-color:#c123de;\n"
"    border-radius:8px;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#ffffff;\n"
"    font-family:Rockwell;\n"
"    font-size:12px;\n"
"    font-weight:bold;\n"
"    padding:13px 32px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #9b14b3;\n"
"}\n"
"QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #a20dbd 5%, #c123de 100%);\n"
"    background-color:#ff6699;\n"
"}\n"
"QPushButton:active {\n"
"    position:relative;\n"
"    top:1px;\n"
"}")
        self.frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        self.checkBox = QtWidgets.QCheckBox(self.frame1)
        self.checkBox.setGeometry(QtCore.QRect(10, 200, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("/*-----QCheckBox-----*/\n"
"QCheckBox\n"
"{\n"
"    background-color: transparent;\n"
"    color: #b9b9bb; /*-----b9b9bb-----*/\n"
"    font-weight: bold;\n"
"    background:transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"    color: #9000FF;\n"
"    background-color: #00111d;\n"
"    border: 1px solid #cc3399;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image: url(:/images/cil-check.png);  /*To replace*/\n"
"    background-color: #cc3399;\n"
"    border: 1px solid #cc3399;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover\n"
"{\n"
"    border: 1px solid #7700b3;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 1px solid #656565;\n"
"\n"
"}")
        self.checkBox.setObjectName("checkBox")
        self.label = QtWidgets.QLabel(self.frame1)
        self.label.setGeometry(QtCore.QRect(130, 199, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setObjectName("label")
        self.label.setOpenExternalLinks(True)
        self.lineEdit = QtWidgets.QLineEdit(self.frame1)
        self.lineEdit.setGeometry(QtCore.QRect(50, 140, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame1)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 70, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.frame1)
        self.pushButton.setGeometry(QtCore.QRect(66, 240, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.frame1)
        self.label_2.setGeometry(QtCore.QRect(50, 126, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame1)
        self.label_3.setGeometry(QtCore.QRect(50, 44, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame1)
        self.pushButton_2.setGeometry(QtCore.QRect(71, 300, 141, 41))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.checkBox.setText(_translate("Dialog", "Recordarme"))
        linkTemplate="<style> a {text-decoration: none; color:purple;}</style> <a href=https://Google.com>¿Olvido su ontraseña?</a>"
        self.label.setText(linkTemplate)
        self.lineEdit.setText(_translate("Dialog", "Password"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Contraseña"))
        self.lineEdit_2.setText(_translate("Dialog", "Username"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "Usuario"))
        self.pushButton.setText(_translate("Dialog", "Iniciar sesion "))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.label_3.setText(_translate("Dialog", "Username"))
        self.pushButton_2.setText(_translate("Dialog", "Crear cuenta"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
